"""papeles a retirar

Revision ID: 3ef5583603bf
Revises: a5ecca730a33
Create Date: 2025-09-09 16:52:35.323199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef5583603bf'
down_revision = 'a5ecca730a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papeles_retirar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('lugar_registro', sa.String(length=100), nullable=False),
    sa.Column('fecha_presentacion', sa.Date(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('papeles_retirar')
    # ### end Alembic commands ###
