"""empty message

Revision ID: a5ecca730a33
Revises: 
Create Date: 2025-08-18 11:15:34.080881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ecca730a33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrega_papeles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=False),
    sa.Column('documentacion_entregada', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gestoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('papeles_recibidos', sa.Text(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('lugar_compra', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculo')
    op.drop_table('gestoria')
    op.drop_table('entrega_papeles')
    # ### end Alembic commands ###
