"""papeles a retirar2

Revision ID: c4d8dabc4800
Revises: 3ef5583603bf
Create Date: 2025-09-09 16:58:51.557489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d8dabc4800'
down_revision = '3ef5583603bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papeles_retirar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patente', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papeles_retirar', schema=None) as batch_op:
        batch_op.drop_column('patente')

    # ### end Alembic commands ###
